services:
  backend:
    build: ./backend
    container_name: mood_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.docker
    volumes:
      - ./backend:/app
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: mood_frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.docker
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:17
    container_name: mood_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mood_tracker
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: