name: Backend CI/CD

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ECR_REPOSITORY: mood-tracker-app/backend
  CONTAINER_NAME: backend-container
  ECS_SERVICE: backend-task-service
  ECS_CLUSTER: mood-tracker-cluster
  ECS_TASK_DEFINITION: backend-task

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci-cd.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Step 3: Build and Push Docker Image, output IMAGE_URI
      - name: Build and Push Docker Image
        id: build_image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          IMAGE_URI=$ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${IMAGE_TAG}
          docker build -t $IMAGE_URI -f backend/Dockerfile backend
          docker push $IMAGE_URI
          echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT
      
      # Step 4: Download current ECS task definition
      - name: Download current ECS task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition ${{ env.ECS_TASK_DEFINITION }} \
            --region ${{ env.AWS_REGION }} \
            --query 'taskDefinition' \
            --output json > task-definition.json

      # Step 5: Clean up unsupported keys from ECS task definition
      - name: Clean up unsupported keys from ECS task definition
        run: |
          jq 'del(.enableFaultInjection) |
              .containerDefinitions |= map(del(.enableFaultInjection))' \
              task-definition.json > clean-task-definition.json

      # Step 6: Render new ECS task definition with updated image
      - name: Render new ECS task definition
        id: task_def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: clean-task-definition.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build_image.outputs.image_uri }}

      # Step 7: Deploy new ECS task definition
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task_def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true